#!/bin/bash

shopt -s extglob

jazzy

git branch -D gh-pages
git checkout --orphan gh-pages
git rm --cached $(git ls-files)

git status --porcelain | cut -d" " -f2 | grep -v docs | xargs rm -Rf
mv docs/* .

git add . 
git commit -am "Update documentation" 

